// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vatsal278/html-pdf-service/internal/handler (interfaces: HtmlPdfServiceHandler)

// Package mock is a generated GoMock package.
package mock

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHtmlPdfServiceHandler is a mock of HtmlPdfServiceHandler interface.
type MockHtmlPdfServiceHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHtmlPdfServiceHandlerMockRecorder
}

// MockHtmlPdfServiceHandlerMockRecorder is the mock recorder for MockHtmlPdfServiceHandler.
type MockHtmlPdfServiceHandlerMockRecorder struct {
	mock *MockHtmlPdfServiceHandler
}

// NewMockHtmlPdfServiceHandler creates a new mock instance.
func NewMockHtmlPdfServiceHandler(ctrl *gomock.Controller) *MockHtmlPdfServiceHandler {
	mock := &MockHtmlPdfServiceHandler{ctrl: ctrl}
	mock.recorder = &MockHtmlPdfServiceHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHtmlPdfServiceHandler) EXPECT() *MockHtmlPdfServiceHandlerMockRecorder {
	return m.recorder
}

// HealthCheck mocks base method.
func (m *MockHtmlPdfServiceHandler) HealthCheck() (string, string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockHtmlPdfServiceHandlerMockRecorder) HealthCheck() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockHtmlPdfServiceHandler)(nil).HealthCheck))
}

// Ping mocks base method.
func (m *MockHtmlPdfServiceHandler) Ping(arg0 http.ResponseWriter, arg1 *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Ping", arg0, arg1)
}

// Ping indicates an expected call of Ping.
func (mr *MockHtmlPdfServiceHandlerMockRecorder) Ping(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockHtmlPdfServiceHandler)(nil).Ping), arg0, arg1)
}
